SocialSolutionMVC_Imobiliaria/Models/ClienteModel.cs
using SocialSolutionMVC_Imobiliaria.Models.Enum;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SocialSolutionMVC_Imobiliaria.Models
{
    public class ClienteModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Digite o nome completo")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Digite o e-mail")]
        [EmailAddress(ErrorMessage = "O e-mail informado não é o valido!")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Digite o CPF")]
        public string Cpf { get; set; }

        [Required(ErrorMessage = "Informe o status do imóvel")]
        public StatusCliente StatusCliente { get; set; }
        public List<ImovelModel> Imoveis { get; set; } = new List<ImovelModel>();

    }
}

SocialSolutionMVC_Imobiliaria/Models/Enum/StatusCliente.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SocialSolutionMVC_Imobiliaria.Models.Enum
{
    public enum StatusCliente
    {
        Inativo = 0,
        Ativo =1
    }
}

SocialSolutionMVC_Imobiliaria/Models/Enum/StatusImovel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SocialSolutionMVC_Imobiliaria.Models.Enum
{
    public enum StatusImovel
    {
        Inativo = 0,
        Ativo = 1
    }
}

SocialSolutionMVC_Imobiliaria/Models/Enum/TipNegocio.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SocialSolutionMVC_Imobiliaria.Models.Enum
{
    public enum TipNegocio
    {
        Aluguel = 0,
        Venda = 1
    }
}

SocialSolutionMVC_Imobiliaria/Models/ErrorViewModel.cs
using System;

namespace SocialSolutionMVC_Imobiliaria.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SocialSolutionMVC_Imobiliaria/Models/HomeModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SocialSolutionMVC_Imobiliaria.Models
{
    public class HomeModel
    {
        public string Nome { get; set; }
        public string Email { get; set; }
    }
}

SocialSolutionMVC_Imobiliaria/Models/ImovelModel.cs
using SocialSolutionMVC_Imobiliaria.Models.Enum;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SocialSolutionMVC_Imobiliaria.Models
{
    public class ImovelModel
    {
        public int Id { get; set; }

//        [Required(ErrorMessage = "Digite o nome completo")]
        public TipNegocio TipoNegocio { get; set; }

//        [Required(ErrorMessage = "Digite o nome completo")]
        public double VlrImovel { get; set; }

//       [Required(ErrorMessage = "Digite o nome completo")]
        public string Desc { get; set; }

//      [Required(ErrorMessage = "Digite o nome completo")]
        public StatusImovel StatusImovel { get; set; }

//      [Required(ErrorMessage = "Digite o nome completo")]
        public ClienteModel Cliente { get; set; }
    }
}

SocialSolutionMVC_Imobiliaria/Controllers/ClientesController.cs
using Microsoft.AspNetCore.Mvc;
using SocialSolutionMVC_Imobiliaria.Models;
using SocialSolutionMVC_Imobiliaria.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SocialSolutionMVC_Imobiliaria.Controllers
{
    public class ClientesController : Controller
    {
        private readonly IClienteRepository _clienteRepository;
        public ClientesController(IClienteRepository clienteRepository)
        {
            _clienteRepository = clienteRepository;
        }
        public IActionResult Index()
        {
            List<ClienteModel> clientes = _clienteRepository.BuscarTodos();
            return View(clientes);
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Criar(ClienteModel cliente)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _clienteRepository.Adicionar(cliente);
                    TempData["MensagemSucesso"] = "Cliente cadastrado com sucesso";
                    return RedirectToAction("Index");

                }
                return View(cliente);

            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar seu contato, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");

            }
        }

        public IActionResult Editar(int id)
        {
            ClienteModel cliente = _clienteRepository.ListarPorId(id);
            return View( cliente);
        }

        [HttpPost]
        public IActionResult Alterar(ClienteModel cliente)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _clienteRepository.Atualizar(cliente);
                    TempData["MensagemSucesso"] = "Cliente atualizado com sucesso";
                    return RedirectToAction("Index");
                }
                return View("Editar", cliente);

            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos atualizar seu contato, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");

            }

        }

        public IActionResult DeletarConfirmacao(int id)
        {
            ClienteModel cliente = _clienteRepository.ListarPorId(id);
            return View(cliente);
        }

        public IActionResult Apagar(int id)
        {
            _clienteRepository.Apagar(id);
            return RedirectToAction("Index");
        }



    }
}

SocialSolutionMVC_Imobiliaria/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SocialSolutionMVC_Imobiliaria.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SocialSolutionMVC_Imobiliaria.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SocialSolutionMVC_Imobiliaria/Controllers/ImoveisController.cs
using Microsoft.AspNetCore.Mvc;
using SocialSolutionMVC_Imobiliaria.Models;
using SocialSolutionMVC_Imobiliaria.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SocialSolutionMVC_Imobiliaria.Controllers
{
    public class ImoveisController : Controller
    {
        private readonly IImovelRepository _imovelRepository;
        public ImoveisController(IImovelRepository imovelRepository)
        {
            _imovelRepository = imovelRepository;
        }

        public IActionResult Index()
        {
            List<ImovelModel> imoveis = _imovelRepository.BuscarTodos();
            return View(imoveis);
        }
        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Criar(ImovelModel imovel)
        {
            //if (ModelState.IsValid)
            //{
                _imovelRepository.Adicionar(imovel);
                return RedirectToAction("Index");
            //}
            //return View(imovel);
        }

        public IActionResult Editar(int id)
        {
            ImovelModel imovel = _imovelRepository.ListarPorId(id);
            return View(imovel);

        }

        [HttpPost]
        public IActionResult Alterar(ImovelModel imovel)
        {
            _imovelRepository.Atualizar(imovel);
            return RedirectToAction("Index");
        }

        public IActionResult DeletarConfirmacao(int id)
        {
            ImovelModel imovel = _imovelRepository.ListarPorId(id);
            return View(imovel);

        }
        public IActionResult Apagar(int id)
        {
            _imovelRepository.Apagar(id);
            return RedirectToAction("Index");
        }



    }
}

SocialSolutionMVC_Imobiliaria/Views/Clientes/Criar.cshtml
@model ClienteModel
@{
    ViewData["Title"] = "Cadastrar Clientes";
}

<div class="text-center">

    <h1 class="display-4">Cadastrar cliente</h1>

</div>

<form asp-controller="Clientes" asp-action="Criar" method="post">

    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome completo">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" asp-for="Email" class="form-control" placeholder="Digite o e-mail">
       @Html.ValidationMessageFor(x => x.Email)
    </div>

    <div class="form-group">
        <label for="cpf">CPF</label>
        <input type="text" asp-for="Cpf" class="form-control" placeholder="Digite o CPF">
        @Html.ValidationMessageFor(x => x.Cpf)

    </div>

    <div class="form-group">
        <label for="status">Status</label>
        <input type="text" asp-for="StatusCliente" class="form-control">
        @Html.ValidationMessageFor(x => x.StatusCliente)

    </div>

    <button type="submit" class="btn btn-primary">Adicionar</button>
    <a class="btn btn-secondary" asp-controller="Clientes" asp-action="Index" role="button">Voltar</a>
</form>

SocialSolutionMVC_Imobiliaria/Views/Clientes/DeletarConfirmacao.cshtml
@model ClienteModel
@{
    ViewData["Title"] = "Deletar Cliente";
}

<div class="text-center">
    <h3 class="display-4">Deseja realmente deletar esse cliente (@Model.Id) ? </h3>
</div>

<a class="btn btn-primary btn-block" role="button" asp-controller="Clientes" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-danger btn-block" role="button" asp-controller="Clientes" asp-action="Apagar" asp-route-id="@Model.Id">Confirmar exclusão</a>

SocialSolutionMVC_Imobiliaria/Views/Clientes/Editar.cshtml
@model ClienteModel
@{
    ViewData["Title"] = "Editar Clientes";
}

<div class="text-center">

    <h1 class="display-4">Editar cliente</h1>

</div>

<form asp-controller="Clientes" asp-action="Alterar" method="post">
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome completo">
        @Html.ValidationMessageFor(x => x.Nome)

    </div>

    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" asp-for="Email" class="form-control" placeholder="Digite o e-mail">
        @Html.ValidationMessageFor(x => x.Email)

    </div>

    <div class="form-group">
        <label for="cpf">CPF</label>
        <input type="text" asp-for="Cpf" class="form-control" placeholder="Digite o CPF">
        @Html.ValidationMessageFor(x => x.Cpf)

    </div>

    <div class="form-group">
        <label for="status">Status</label>
        <input type="text" asp-for="StatusCliente" class="form-control">
        @Html.ValidationMessageFor(x => x.StatusCliente)

    </div>

    <button type="submit" class="btn btn-primary">Alterar</button>
    <a class="btn btn-secondary" asp-controller="Clientes" asp-action="Index" role="button">Voltar</a>
</form>

SocialSolutionMVC_Imobiliaria/Views/Clientes/Index.cshtml
@model List<ClienteModel>
@{
    ViewData["Title"] = "Listagem de Clientes";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-success" role="button" asp-controller="Clientes" asp-action="Criar">Adicionar</a>
    </div>
    <br />

    @if (TempData["MenssagemSucesso"] != null)
    {

        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert"> X</button>
        </div>
    }
    @if (TempData["MenssagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert"> X</button>
        </div>
    }


    <h1 class="display-4">Listagem de clientes</h1>


    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
                <th scope="col">CPF</th>
                <th scope="col">Status</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (ClienteModel cliente in Model)
                {
                    <tr>
                        <th scope="row">@cliente.Id</th>
                        <td>@cliente.Nome</td>
                        <td>@cliente.Email</td>
                        <td>@cliente.Cpf</td>
                        <td>@cliente.StatusCliente</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-controller="Clientes" asp-action="Editar" asp-route-id="@cliente.Id">Editar</a> |
                                <a role="button" class="btn btn-danger" asp-controller="Clientes" asp-action="DeletarConfirmacao" asp-route-id="@cliente.Id">Apagar</a>
                            </div>
                        </td>

                    </tr>

                }
            }
        </tbody>
    </table>
</div>

SocialSolutionMVC_Imobiliaria/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem-Vindo!</h1>
    <p>Sistema de controle de Imobiliária</p>
</div>

SocialSolutionMVC_Imobiliaria/Views/Imoveis/Criar.cshtml
@model ImovelModel
@{
    ViewData["Title"] = "Cadastrar Imoveis";
}

<div class="text-center">

    <h1 class="display-4">Cadastrar imóveis</h1>

</div>

<form asp-controller="Imoveis" asp-action="Criar" method="post">
    <div class="form-group">
        <label for="tipNegocio">Tipo de Negócio</label>
        <input type="text" asp-for="TipoNegocio" class="form-control" placeholder="Digite o Tipo de Negócio">
        @Html.ValidationMessageFor(x => x.TipoNegocio)

    </div>

    <div class="form-group">
        <label for="VlrImovel">Valor Imovel</label>
        <input type="number" asp-for="VlrImovel" class="form-control" placeholder="Digite o valor">
        @Html.ValidationMessageFor(x => x.VlrImovel)
    </div>

    <div class="form-group">
        <label for="Desc">Descrição</label>
        <input type="text" asp-for="Desc" class="form-control" placeholder="Informe a descrição">
        @Html.ValidationMessageFor(x => x.Desc)
    </div>

    <div class="form-group">
        <label for="status">Status</label>
        <input type="text" asp-for="StatusImovel" class="form-control">
        @Html.ValidationMessageFor(x => x.StatusImovel)
    </div>

    <div class="form-group">
        <label for="cliente">Cliente</label>
        <input type="text" asp-for="Cliente" class="form-control">
        @Html.ValidationMessageFor(x => x.StatusImovel)
    </div>


    <button type="submit" class="btn btn-primary">Adicionar</button>
    <a class="btn btn-secondary" asp-controller="Imoveis" asp-action="Index" role="button">Voltar</a>
</form>

SocialSolutionMVC_Imobiliaria/Views/Imoveis/DeletarConfirmacao.cshtml
@model ImovelModel
@{
    ViewData["Title"] = "Deletar Imoveis";
}

<div class="text-center">
    <h3 class="display-4">Deseja realmente deletar este imóvel (@Model.Id) ? </h3>
</div>

<a class="btn btn-primary btn-block" role="button" asp-controller="Imoveis" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-danger btn-block" role="button" asp-controller="Imoveis" asp-action="Apagar" asp-route-id="@Model.Id">Confirmar exclusão</a>

SocialSolutionMVC_Imobiliaria/Views/Imoveis/Editar.cshtml
@model ImovelModel
@{
    ViewData["Title"] = "Cadastrar Imoveis";
}

<div class="text-center">

    <h1 class="display-4">Cadastrar imóveis</h1>

</div>

<form asp-controller="Imoveis" asp-action="Alterar" method="post">
     <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label for="tipNegocio">Tipo de Negócio</label>
        <input type="text" asp-for="TipoNegocio" class="form-control" placeholder="Digite o Tipo de Negócio">
    </div>

    <div class="form-group">
        <label for="VlrImovel">Valor Imovel</label>
        <input type="number" asp-for="VlrImovel" class="form-control" placeholder="Digite o valor">
    </div>

    <div class="form-group">
        <label for="Desc">Descrição</label>
        <input type="text" asp-for="Desc" class="form-control" placeholder="Digite o CPF">
    </div>

    <div class="form-group">
        <label for="status">Status</label>
        <input type="text" asp-for="StatusImovel" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Alterar</button>
    <a class="btn btn-secondary" asp-controller="Imoveis" asp-action="Index" role="button">Voltar</a>

</form>

SocialSolutionMVC_Imobiliaria/Views/Imoveis/Index.cshtml
@model List<ImovelModel>
@{
    ViewData["Title"] = "Listagem de Imóveis";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-success" role="button" asp-controller="Imoveis" asp-action="Criar">Adicionar</a>
    </div>
    <br />
    @if (TempData["MenssagemSucesso"] != null)
    {

        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert"> X</button>
            This is a success alert—check it out!
        </div>
    }
    @if (TempData["MenssagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert"> X</button>

            This is a danger alert—check it out!
        </div>
    }
    <h1 class="display-4">Listagem de Imóveis</h1>


    <table class="table">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">Tipo Negocio</th>
                <th scope="col">Valor Imóvel</th>
                <th scope="col">Desc</th>
                <th scope="col">Status</th>
                <th scope="col">Cliente</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                @foreach (ImovelModel imovel in Model)
                {
                    <tr>
                        <th scope="row">@imovel.Id</th>
                        <td>@imovel.TipoNegocio</td>
                        <td>@imovel.VlrImovel</td>
                        <td>@imovel.Desc</td>
                        <td>@imovel.StatusImovel</td>
                        <td>@imovel.Cliente</td>

                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-controller="Imoveis" asp-action="Editar" asp-route-id="@imovel.Id">Editar</a> |
                                <a role="button" class="btn btn-danger" asp-controller="Imoveis" asp-action="DeletarConfirmacao" asp-route-id="@imovel.Id">Apagar</a>
                            </div>
                        </td>

                    </tr>

                }
            }
        </tbody>
    </table>
</div>

SocialSolutionMVC_Imobiliaria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]Social Solution Imobiliaria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Social Solution Imobiliaria</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Principal</a>
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Cliente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Imoveis" asp-action="Index">Imóvel</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Social Solution Imobiliaria
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>